Practical_projects/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from user_manage.views import depart,user,admin,account,task,Order,chart,upload

# 添加一个
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings



urlpatterns = [

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # path('admin/', admin.site.urls),
    path('', depart.depart_list, name='index'),
    path('depart/list/',depart.depart_list),
    path('depart/add/',depart.depart_add),
    path('depart/delete/',depart.depart_delete),

    # 支持xxxx/depart/<int: nid>/edit/ 显示
    path('depart/<int:nid>/edit/', depart.depart_edit),
    # path('/<int:nid>/edit/', depart.depart_edit),

    # 用户管理
    path('user/list/', user.user_list,name='user_list_redirect'),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/delete/',user.user_delete),

    # 管理员
    path('admin/list/',admin.admin_list),
    path('admin/add/',admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 任务管理

    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),


    # 订单管理
    path('Order/list/', Order.Order_list),
    path('Order/add/', Order.Order_add),
    path('Order/delete/', Order.Order_delete),
    path('Order/detail/', Order.Order_detail),
    path('Order/edit/', Order.Order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    path('chart/fold/', chart.chart_fold),
    # path('chart/map/', chart.chart_map),


    # 文件上传
    path('upload/list/', upload.upload_list),
    path('upload/multi/', upload.upload_multi),
    path('upload/form/', upload.upload_form),

    path('upload/model_form/add/', upload.upload_model_form_add),
    path('upload/model_form/list/', upload.upload_model_form_list),

    





]

user_manage/views/Order.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: Order.py
@time: 2023/4/26  16:13
"""
import random
from datetime import datetime
import json

from django.http import JsonResponse
from django.shortcuts import render,HttpResponse
from django.views.decorators.csrf import csrf_exempt

from user_manage import models
from user_manage.utils.bootstrap import BootStrapModelForm
from user_manage.utils.pagination import Pagination


class OrderModelForm(BootStrapModelForm):

    class Meta:
        model=models.Order
        # fields='__all__'
        exclude = ('oid','username')   # exclude = ["oid"]  两种方式 不显示oid

def Order_list(request):

    queryset=models.Order.objects.all().order_by('-id')
    form=OrderModelForm() #获取 添加表单信息

    # 分页
    page_object = Pagination(request, queryset,page_size=5)
    context={
        'form':form,
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html(),  # 生成页码
    }
    # print(context)


    return render(request,'Order_list.html',context)


# post请求一定要传csrf 验证
@csrf_exempt
def Order_add(request):

    form = OrderModelForm(data=request.POST)
    '''form.is_valid()用于验证表单数据是否合法，如果数据合法则返回 True，否则返回 False。'''
    if form.is_valid():

        form.instance.oid=datetime.now().strftime("%Y-%m-%d-%H%M")+"$"+str(random.randint(100,999))
        # 从session中取当前用户id
        form.instance.username_id=request.session["info"].get('id')

        form.save()
        data_dict = {"status": True}

        #等价
        # return HttpResponse(json.dumps(data_dict))
        return JsonResponse(data_dict)



    data_dict = {"status": False, 'error': form.errors}
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))


def Order_delete(request):
    '''删除订单'''

    uid=request.GET.get('uid')
    # uid=1111
    print(uid)
    # 判断是否存在
    exists = models.Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({"status":False ,"error":"数据不存在,删除失败."})
    
    models.Order.objects.filter(id=uid).delete()
    return JsonResponse({'status':True})


def Order_detail(request):
    '''更具id获取编辑对象'''
    uid=request.GET.get('uid')
    print(uid)

    '''第一种方式通过返回的数据对象一个个获取所需要的字段信息'''
    # row_object= models.Order.objects.filter(id=uid).first()
    # if not row_object:
    #     return JsonResponse({'status':False,'message':'订单ID不存在'})
    
    # result={
    #     'status':True,
    #     "data":{
    #     'title':row_object.title,
    #     'price':row_object.price,
    #     'status':row_object.status
    #     }
    # }

    '''第二种方法,直接获取对象返回的json格式数据'''
    row_object= models.Order.objects.filter(id=uid).values('title','price','status').first()
    if not row_object:
        return JsonResponse({'status':False,'message':'订单ID不存在'})
    
    result={
        'status':True,
        "data":row_object
    }

    return JsonResponse(result)

# post请求一定要传csrf 验证
@csrf_exempt
def Order_edit(request):

    uid=request.GET.get('uid')
    row_object= models.Order.objects.filter(id=uid).first()
    print(row_object)
    '''form.is_valid()用于验证表单数据是否合法，如果数据合法则返回 True，否则返回 False。'''

    if not row_object:
        return JsonResponse({'status':False,'edit_messages':'订单ID不存在'})


    form=OrderModelForm(data=request.POST,instance=row_object)
    if form.is_valid():

        # row_object.instance.oid=datetime.now().strftime("%Y-%m-%d-%H%M")+"$"+str(random.randint(100,999))

        # # 从session中取当前用户id
        # row_object.instance.username_id=request.session["info"].get('id')

        form.save()
        data_dict = {"status": True}

        #等价
        # return HttpResponse(json.dumps(data_dict))
        return JsonResponse(data_dict)

  
    #  如果 返回的值不满足校验 is_valid 返回错误信息
    data_dict = {"status": False, 'error': form.errors}
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))

user_manage/views/account.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: account.py
@time: 2023/4/24  13:52
"""
from django import forms

from django.shortcuts import render, redirect,HttpResponse

from  user_manage import  models
from user_manage.utils.bootstrap import BootStrapForm
from user_manage.utils.encrypt import md5
from user_manage.utils.Verifiy_code import check_code


class LoginForm(BootStrapForm):
    pass
    name = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={'class':'form-control'}),

        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )

    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    # 将输入的密码转化为md5格式
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form=LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data,'填写信息')

        # 验证码的校验
        user_input_code=form.cleaned_data.pop('code')
        code = request.session.get('image_code','')
        # print(user_input_code,code)
        if code.upper() != user_input_code.upper(): # upper()转大写
            form.add_error('code','验证码错误')
            return render(request, 'login.html', {'form': form})

        # 验证成功，获取到的用户名和密码
        # {'name': 'wupeiqi', 'password': '123',"code":123}
        # {'name': 'wupeiqi', 'password': '5e5c3bad7eb35cba3638e145c830c35f',"code":xxx}
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")# 主动往form中添加错误信息
            # form.add_error("name", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.name}
        # session可以保存2小时
        request.session.set_expiry(60 * 60 *2)

        return redirect("/admin/list/")

    return render(request, 'login.html', {'form': form})


def logout(request):
    '''注销'''
    request.session.clear()
    return redirect('/login/')


def image_code(request):
    '''生成图片验证码'''

    # 从内存中读取文件
    from io import BytesIO
    img,code_string=check_code()
    print(img,code_string)

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream=BytesIO()
    img.save(stream,'png')
    # stream.getvalue()

    return HttpResponse(stream.getvalue())

user_manage/views/admin.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: admin.py
@time: 2023/4/23  15:29
"""
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404

from user_manage.utils import pagination
from user_manage import models
from user_manage.models import Admin

from user_manage.utils.bootstrap import BootStrapModelForm
from user_manage.utils.encrypt import md5

def admin_list(request):
    '''管理员列表'''

    '''来源是account登录操作传送info到数据库 获取session中的info值 
        也可以直接再html中调用
    '''
    # print(request.session['info'])

    # 构造搜索
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["name__contains"] = search_data

    # 根据搜索条件去数据库获取
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_obj=pagination.Pagination
    page_object = page_obj(request, queryset,page_size=5)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        "search_data": search_data
    }
    return render(request, 'admin_list.html', context)

class Admin_add_ModelForm(BootStrapModelForm):

    # 在modelform中添加新字段 常用于确认事件
    confirm_password=forms.CharField(
        label='确认密码',
        # 脱敏操作  # render_value=False报错时不清除数据
        widget=forms.PasswordInput(render_value=False)
    )

    class Meta:
        model = models.Admin
        fields =['name','password','confirm_password']
        # widgets={
            # 'password':forms.PasswordInput(render_value=True) #报错时不清除数据
        # }

    # 密码进行MD5加密
    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    # 校验密码是否一直
    def clean_confirm_password(self):
        print(self.cleaned_data) #{'name': 'carlos', 'password': '2ac77fdb13b12f63aabc6658b3834032', 'confirm_password': '22211'}

        pwd=self.cleaned_data.get('password')
        confirm_pwd=md5(self.cleaned_data.get('confirm_password'))# 对确认密码MD5加密，保证前端传入值为密文

        if confirm_pwd!=pwd:
            raise ValidationError(f'两次输入的密码不一致\n请重新输入')

        # return 什么 次字段返回数据库值就会是什么
        return confirm_pwd

class Admin_edit_ModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields =['name']
        widgets={
            # 'password':forms.PasswordInput(render_value=True) #报错时不清除数据
        }

def admin_add(request):
    '''添加管理员'''

    html_title='新建管理员'
    if   request.method == "GET":
        model_forms=Admin_add_ModelForm

        return render(request,'change.html',{'form':model_forms,'title':html_title})

    model_forms = Admin_add_ModelForm(data=request.POST)
    if model_forms.is_valid():

        model_forms.save()
        return redirect('/admin/list/')

    return render(request, 'change.html', {'form': model_forms, "title": html_title})


def admin_edit(request,nid):
    '''编辑管理员'''

    # 对象 /None 先判断是否有对应的数据
    input_obj=models.Admin.objects.filter(id=nid).first()
    if not input_obj:
        return render(request,'error.html',{"msg":"没有找到对应的用户"})

    html_title = '编辑管理员'
    if   request.method == "GET":
        model_forms=Admin_edit_ModelForm(instance=input_obj)# 默认值
        return render(request,'change.html',{'form':model_forms,'title':html_title})

    model_forms =Admin_edit_ModelForm(data=request.POST,instance=input_obj)
    if model_forms.is_valid():

        model_forms.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': model_forms, "title": '傻逼为什么姓名都不填'})

def admin_delete(request,nid):

    # 对象 /None 先判断是否有对应的数据
    input_obj = models.Admin.objects.filter(id=nid).first()
    if not input_obj:
        return render(request, 'error.html', {"msg": "没有找到对应的用户"})

    admin = get_object_or_404(Admin, id=nid)
    admin.delete()

    # 返回到管理员列表 重定向
    return redirect(f"/admin/list")

def admin_reset(request,nid):
    # 对象 /None 先判断是否有对应的数据
    input_obj = models.Admin.objects.filter(id=nid).first()
    if not input_obj:
        return render(request, 'error.html', {"msg": "没有找到对应的用户"})

    # 重置密码为123456，并进行md5加密
    input_obj.password=md5('123456')
    print('加密后',input_obj.password)
    input_obj.save()

    # 返回到管理员列表 重定向
    return redirect(f"/admin/list")

user_manage/views/chart.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: chart.py
@time: 2023/5/5  14:01
"""

from django import forms
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from user_manage import models

def chart_list(request):

    return render(request,'chart.html')


def chart_bar(request):


    legend= ['销量','业绩']
    x_axis= ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']
    series_list= [
            {
              'name': '销量',
              'type': 'bar',
              'data': [5, 20, 36, 10, 10, 20]
            },
            {
              'name': '业绩',
              'type': 'bar',
              'data': [50, 6, 33, 100, 10, 25]
            }
          ]
       
    result={
        'status':True,
        'data':{
            'legend':legend,
            'x_axis':x_axis,
            'series_list':series_list,
        }
    }

    # print(result)

    return JsonResponse(result)


def chart_pie(request):

    # series_list=[
    #     { 'value': 1048, 'name': '人事部' },
    #     { 'value': 735, 'name': '研发部' },
    #     { 'value': 580, 'name': '外贸部' },
    #     { 'value': 484, 'name': '保安部' },
    #     { 'value': 300, 'name': 'CBO' }
    #   ]

    # 获取数据库的值 赋值到饼图上
    data=models.performance.objects.all()
    series_list=[]
    for obj in data:
        dict={ 'value': obj.sales ,'name': obj.depart }
        series_list.append(dict)

        # print(obj.sales,obj.depart)


    result={
    'status':True,
    'data':{
        'series_list':series_list,
    }
}

    return JsonResponse(result)

def chart_fold(request):

    result={
            'status':True,
            'data':{
                
            }
        }


    return JsonResponse(result)

# def chart_map(request):

#         return JsonResponse(result)

user_manage/views/depart.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: depart.py
@time: 2023/4/23  13:38
"""

from django.core.exceptions import ValidationError
from django.forms import forms
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from user_manage import models
from django.core.paginator import Paginator

def index(request):
    return HttpResponse("Hello, world. This is the user_manage app.")

def depart_list(request):
    """ 部门列表 """

    # 去数据库中获取所有的部门列表
    #  [对象,对象,对象]
    queryset = models.Department.objects.all().order_by('-id')

    # 添加分页功能
    per_page = 10
    paginator = Paginator(queryset, per_page)
    page = request.GET.get('page')
    objs = paginator.get_page(page)
    queryset=objs

    return render(request, 'depart_list.html', {'queryset': queryset})


def depart_add(request):
    """ 部门添加 """
    if request.method=='GET':
        return render(request, 'depart_add.html')

    # 获取用户通过post请求传来的信息
    title = request.POST.get('title')
    # 保存到数据库
    models.Department.objects.create(title=title)
    # 返回到部门列表 重定向
    # return redirect("/depart/list/")
    return redirect("/depart/add/")


def depart_delete(request):
    """ 删除部门 """
    nid =request.GET.get('nid')
    page=request.GET.get('page')

    # 删除操作
    models.Department.objects.filter(id=nid).delete()

    # 返回到部门列表 重定向
    return redirect(f"/depart/list?page={page}")


def depart_edit(request,nid):# nid 直接从urls中获取
    """ 部门编辑 """

    if request.method == "GET":
        # 根据nid，获取他的数据 [obj,]
        edit_obj = models.Department.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html', {"edit_obj": edit_obj})


    # 1.获取用户提交的标题，2.数据库更新，3.重定向返回列表
    depart_title = request.POST.get("depart_title")
    models.Department.objects.filter(id=nid).update(title=depart_title)
    return redirect('/depart/list')

user_manage/views/index.py
#!usr/bin/env python
# -*- coding:utf-8 _*-
"""
@author:carlos
@file: index.py
@time: 2023/4/23  13:39
"""

from django.core.exceptions import ValidationError
from django.forms import forms
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from user_manage import models
from django.core.paginator import Paginator

def index(request):
    return HttpResponse("Hello, world. This is the user_manage app.")

user_manage/templates/change.html
{% extends 'layout.html' %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

user_manage/templates/chart.html
{% extends 'layout.html' %}
<!-- 注意格式不能错 %与{} -->
{% load static %} 

{% block content %}

<div class="container">

    {% block echarts %}  {% endblock %} 

        
    <div class="panel panel-default">
        <div class="panel-heading">柱状图</div>
        <div class="panel-body">

                <!-- 为 ECharts 准备一个定义了宽高的 DOM -->
                <div id="m_fold" style="width: 1000px;height:400px;"></div>
         

        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-7">
            <div class="panel panel-default">
                <div class="panel-heading">柱状图</div>
                <div class="panel-body">
                    
                 
                        <!-- 为 ECharts 准备一个定义了宽高的 DOM -->
                        <div id="m1" style="width: 400px;height:400px;"></div>
                
                </div>
            </div>
        </div>

        <div class="col-sm-5">
            <div class="panel panel-default">
                <div class="panel-heading">饼图</div>
                    <div class="panel-body">
                  
                            <!-- 为 ECharts 准备一个定义了宽高的 DOM -->
                            <div id="m_pie" style="width: 400px;height:400px;"></div>
                 
                    </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}



{% block js %}

    <script src="{% static 'js/echarts.js' %} " ></script>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var Chart_bar = echarts.init(document.getElementById('m1'));
  
        // 指定图表的配置项和数据
        var option_bar = {
            title: {
            text: 'ECharts 树状图',
            subtext: "副标题",
            subtextStyle: {
                fontSize: 10,
                align: "left"
                },
          },
          tooltip: {},
          legend: {
            data: [] //后台配置
          },
          xAxis: {
            data: [] //后台配置
          },
          yAxis: {},
          series: [] //后台配置

        };
        
        // 发送ajax请求获取，获取后台传输的数据
        $.ajax({
            url:'/chart/bar/',
            type:'get',
            dataType:'JSON',
            success:function (res){
                // 将后台返回的数据，更新到option中
                if (res.status){
                    option_bar.legend.data=res.data.legend;
                    option_bar.xAxis.data=res.data.x_axis;
                    option_bar.series = res.data.series_list;
                    // console.log(option_bar.series)
                 

                    //指定刚才使用的配置项和数据显示图表
                    Chart_bar.setOption(option_bar);
                }
            }
        })

       
      </script>

    <!-- 饼图 -->
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var Chart_pie = echarts.init(document.getElementById('m_pie'));

        // 指定图表的配置项和数据
        var option_pie = {

            title: {
                text: 'ECharts 饼图',
                // subtext: "部门",
                // textAlign:'center',
                // left:'center',
                // textVerticalAlign: "center"
            },
            tooltip: {
                trigger: 'item'
            },
            legend: {
                top: '5%',
                left: '10%',
                show: true //legend显示开关
            },
            series: [
                {
                name: 'kpi指标',
                type: 'pie',
                radius: ['40%', '70%'],
                avoidLabelOverlap: false,
                itemStyle: {
                    borderRadius: 10,
                    borderColor: '#fff',
                    borderWidth: 2
                },
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                    show: true,
                    fontSize: 40,
                    fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [] //后台配置
            //     data: [
            //     { value: 1048, name: 'Search Engine' },
            //     { value: 735, name: 'Direct' },
            //     { value: 580, name: 'Email' },
            //     { value: 484, name: 'Union Ads' },
            //     { value: 300, name: 'Video Ads' }
            // ]
                }
            ]
            };
    
        
        // 发送ajax请求获取，获取后台传输的数据
        $.ajax({
            url:'/chart/pie/',
            type:'get',
            dataType:'JSON',
            success:function (res){
                // 将后台返回的数据，更新到option中
                if (res.status){
                    option_pie.series[0].data = res.data.series_list; //注意是路径 .series[0].data
                    // console.log(option_pie.series[0].data,res.data.series_list)
                

                    //指定刚才使用的配置项和数据显示图表
                    Chart_pie.setOption(option_pie);
                }
            }
        })

    
    </script>

    <!-- 折线图 -->
    <script type="text/javascript">
        var Chart_fold = echarts.init(document.getElementById('m_fold'));
        var option;

        option = {
        title: {
            text: 'ECharts 折线图'
        },
        tooltip: {
            trigger: 'axis'
        },
        legend: {
            data: ['Email', 'Union Ads', 'Video Ads', 'Direct', 'Search Engine']
        },
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        toolbox: {
            feature: {
            saveAsImage: {  
                name: 'Carlos的折线图',    //保存图片名称
                type: 'png' //保存图片格式
                        }
            }
        },
        xAxis: {
            type: 'category',
            boundaryGap: false,
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
        },
        yAxis: {
            type: 'value'
        },
        series: [
            {
            name: 'Email',
            type: 'line',
            stack: 'Total',
            data: [120, 132, 101, 134, 90, 230, 210]
            },
            {
            name: 'Union Ads',
            type: 'line',
            stack: 'Total',
            data: [220, 182, 191, 234, 290, 330, 310]
            },
            {
            name: 'Video Ads',
            type: 'line',
            stack: 'Total',
            data: [150, 232, 201, 154, 190, 330, 410]
            },
            {
            name: 'Direct',
            type: 'line',
            stack: 'Total',
            data: [320, 332, 301, 334, 390, 330, 320]
            },
            {
            name: 'Search Engine',
            type: 'line',
            stack: 'Total',
            data: [820, 932, 901, 934, 1290, 1330, 1320]
            }
        ]
        };
        

        //指定刚才使用的配置项和数据显示图表
        Chart_fold.setOption(option);
    </script>

{% endblock %}

user_manage/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"> 修改部门 </h1>
            </div>
            <div class="panel-body">
                <form method="post">
<!--                    post请求需要的操作，传一个django需要传的值-->
                    {% csrf_token %}
                    <div class="form-group">
                        <label>部门名称</label>
                        <input type="text" class="form-control" placeholder="标题" name="depart_title"
                               value="{{ edit_obj.title }}"/>
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user_manage/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>

    <!--设备背景图片、颜色、透明度、元素优先级-->
    <style>
              .bg-image {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-image: url('{% static 'img/清馨小美女.jpg' %}');
                background-repeat: no-repeat;
                background-size: cover;
                opacity: 0.3; /* 背景图片透明度，范围从 0 ~ 1 */
                z-index: -1; /* 将背景图元素的 z-index 属性设置为较小的值 */
                }

                  .content {
                    position: relative;
                    z-index: 1; /* 给其他元素设置较大的 z-index 值 */
                  }
        </style>
    <div class="bg-image"></div>

</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名 </label>
            {{ form.name }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>

        <!-- 图形验证码-->
        <div class="form-group">
            <label for="id_code">验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;" onclick="refresh_code();">
                </div>
            </div>
        </div>
          <!-- 点击刷新验证码操作-->
        <script>
            function refresh_code() {
                var image = document.getElementById('image_code');
                var new_url = image.src + '?' + Math.random();
                image.src = new_url;
            }
        </script>

        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

user_manage/templates/upload_batch.html
{% extends 'user_list.html' %}

{% block user_list %}

{% endblock %}